davlatlar = ['O`zbekistom','Belarus','Russia','Malayziya','Germaniya','Fransiya']
print(len(davlatlar))
print(sorted(davlatlar))
print(sorted(davlatlar, reverse=True))
print(davlatlar)
davlatlar.reverse()
print(davlatlar)
davlatlar.sort()
print(davlatlar)
davlatlar.sort(reverse=True)
print(davlatlar)
juft_sonlar = list(range(120,1200,2))
print(juft_sonlar)
print(sum(juft_sonlar))
print(max(juft_sonlar)-min(juft_sonlar))
print(len(juft_sonlar))
print(juft_sonlar[:20])
print(juft_sonlar[-20:])
print(juft_sonlar[260:280])

taomlar = ['osh','manti','sho`rva','shashlik','qozon kebab']
nonushta = taomlar[:]
nonushta.remove('manti')
nonushta.remove('shashlik')
nonushta.remove('qozon kebab')
nonushta.append('somsa')
nonushta.append('lagman')
print(nonushta)
print(taomlar)
nonushta.append('qaymoq va non')
print(nonushta)